#!/bin/sh
#
# Maybe register Chef server's client with server, update runlist from metadata

# Cloud-init directory where this will be placed as MIME part
# (instance is a symlink to instances/$INSTANCE_UUID)

SCRIPTS=/var/lib/cloud/instance/scripts

# Exit without doing anything if no arguments given (cloud-init part-handler)
if [ $# != 1 ]; then
    echo >&2 "Usage: $0 INSTANCE"
    [ $# = 0 ]
    exit $?
fi
INSTANCE=$1

# redirect standard output and error to console log and cloud-init-output log
exec 2>&1 | tee -a /dev/console /var/log/cloud-init-output.log

# send log output from chef directly to /dev/console to eliminate buffering
# (log will not be preserved, but chef-client will run again soon enough)
OPTS="-L /dev/console"

# cloud-init does not set HOME, but it is needed for chef-server cookbook
export HOME=/root

# get roles and recipes
roles=
recipes=
eval "`$SCRIPTS/getconfig.py`"

expand() {
    TYPE=$1
    ITEMS=
    eval echo '$'"$TYPE"s | tr , '\n' |
        {
            while read ITEM
            do
                case $ITEM in
                    *[A-Za-z]*)
                        ITEM=$TYPE'['$ITEM']'
                        if [ -z "$ITEMS" ]; then
                            ITEMS="$ITEM"
                        else
                            ITEMS="$ITEMS,$ITEM"
                        fi
                        ;;
                esac
            done
            if [ -n "$ITEMS" ]; then
                if [ -z "$RUNLIST" ]; then
                    echo "$ITEMS"
                else
                    echo "$RUNLIST,$ITEMS"
                fi
            fi
        }
}

RUNLIST=

NEWRUNLIST=`expand recipe`
if [ -n "$NEWRUNLIST" -a "$NEWRUNLIST" != "$RUNLIST" ]; then
    chef-client $OPTS --runlist $NEWRUNLIST && RUNLIST=$NEWRUNLIST
fi

# role may not be present if restore failed, make a second pass
NEWRUNLIST=`expand role`
if [ -n "$NEWRUNLIST" -a "$NEWRUNLIST" != "$RUNLIST" ]; then
    chef-client $OPTS --runlist $NEWRUNLIST && RUNLIST=$NEWRUNLIST
fi

# add role based on instance name, if it exists
roles=$INSTANCE
NEWRUNLIST=`expand role`
if [ -n "$NEWRUNLIST" -a "$NEWRUNLIST" != "$RUNLIST" ]; then
    chef-client $OPTS --runlist $NEWRUNLIST && RUNLIST=$NEWRUNLIST
fi

# failsafe attempt to run common role if nothing else specified
if [ -z "$RUNLIST" ]; then
    chef-client $OPTS --runlist 'role[common]'
fi
