#!/bin/sh
#
# Set up (if not already present) SSH ECDSA deploy key
#

# Cloud-init directory where this will be placed as MIME part
# (instance is a symlink to instances/$INSTANCE_UUID)

SCRIPTS=/var/lib/cloud/instance/scripts

# Exit without doing anything if no arguments given (cloud-init part handler)
if [ $# != 2 ]; then
    echo >&2 "Usage:  $0 USER METAKEY"
    echo >&2 "    e.g $0 root deploykey"
    [ $# = 0 ]
    exit $?
fi

USER=$1
METAKEY=$2

# get ECDSA key from metadata; explicit 'meta' argument needed to unsuppress key
eval "`$SCRIPTS/getconfig.py meta`"

# yes, that's two levels of quoting around the key to preserve newlines
export KEY="`eval echo '"$'$METAKEY'"'`"

sudo -HE -u $USER sh -ec '
    umask 077
    mkdir -p "$HOME/.ssh"
    KFILE=$HOME/.ssh/id_ecdsa
    echo "$KEY" > "$KFILE"
    chmod 600 "$KFILE"
    ssh-keygen -y -f "$KFILE" | sed "s/\$/ $USER@`hostname -f`/" > "$KFILE.pub"
    chmod 644 "$KFILE.pub"
'
